#!/bin/bash

# CUDA=${DOCKER_TAG%-*}
# CUDA_VERSION=${CUDA##cu}

# PYTHON=${DOCKER_TAG##*-}
# PYTHON_VERSION=${PYTHON##py}

if [ $DOCKER_TAG == "latest" ]
then
  docker build  -f $DOCKERFILE_PATH -t $IMAGE_NAME .
else
  docker build --build-arg CUDA_VERSION=${DOCKER_TAG} -f $DOCKERFILE_PATH -t $IMAGE_NAME .
fi